# Change these first
owner: PaoMian0806 # Your GitHub organization or username, where this repository lives
repo: Wikidot-Upptime-Status # The name of this repository

sites:
  - name: Wikidot
    url: https://www.wikidot.com
  - name: SCP-ZHTR
    url: http://scp-zh-tr.wikidot.com
  - name: SCP-EN
    url: https://scp-wiki.wikidot.com
  - name: SCP-JP
    url: http://scp-jp.wikidot.com
  - name: Backrooms
    url: http://backrooms-wiki.wikidot.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /Wikidot-Upptime-Status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Wikidot Status Page
  introTitle: "**Wikidot**相關網站監測"
  introMessage: 這是一個可以即時顯示Wikidot網站運行狀況的頁面，以Upptime這個開源網站監測專案為基底去設置，目前由Pao Mian本人託管並維護。目前本頁收錄了Wikidot主頁、部分的SCP Wiki國際站以及Backrooms Wiki，之後可能會添加其他網站。
  navbar:
    - title: Main
      href: https://paomian0806.github.io/Wikidot-Upptime-Status
    - title: GitHub
      href: https://github.com/PaoMian0806/Wikidot-Upptime-Status
    - title: Wikidot
      href: https://www.wikidot.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
